services:

  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 10086:10086
    environment:
      - DB_HOST=db
      - DB_NAME=webapp
      - DB_USERNAME=webb
      - DB_PASSWORD=PLEASEDONTLEAKMYPASSWORDXDDDD!!!
      - DB_PORT=5432
      - SERVER_PORT=10086
      - FLASK_SECRET=DONTSTEALMYKEYPL0XXD567!!!@@@
      - ENCRYPT_KEY=3E9DTp80EJCpmvvRd8rgBacww7itTR3sg9mqGKxxqktZOprxANJiXFyQ5V5zCH2oqru6sAllMuOfbsnIw742wOuOCSkdYZdR1cKDiMLKIxbPhEiNze7Ee3p7KdFTbwM2qr3fuB9ffPwNAZ2zQYo0UJQUlJ53zriMtqmnpCVSpYdrwhH2AFHJSLgbqOZAqbBXzO6DiyAmdcYz4zzJQvxPFIg9RLX2y07uislFqcx5FuM0lzYxUXoLIyahvV04noV9
    depends_on:
      - db

  db:
    container_name: db
    image: 'postgres@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c'
    environment:
      POSTGRES_USER: webb
      POSTGRES_PASSWORD: PLEASEDONTLEAKMYPASSWORDXDDDD!!!
      POSTGRES_DB: webapp
    expose:
      - 5432:5432
    


