apiVersion: v1
kind: Namespace
metadata:
  name: lost-pyramid

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-pyramid
  namespace: lost-pyramid
  labels:
    chal: lost-pyramid
spec:
  selector:
    matchLabels:
      chal: lost-pyramid
  template:
    metadata:
      labels:
        chal: lost-pyramid
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: lost-pyramid
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        ports:
        - containerPort: 8050
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false

---
apiVersion: v1
kind: Service
metadata:
  name: lost-pyramid
  namespace: lost-pyramid
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:058264123223:certificate/614551b1-8738-4648-9db2-9fb2b502f715
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8050
  selector:
    chal: lost-pyramid


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lost-pyramid
  namespace: lost-pyramid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lost-pyramid
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-other-namespaces
  namespace: lost-pyramid
spec:
  podSelector:
    matchLabels:
      chal: lost-pyramid
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}  # Allow traffic only from within the same namespace
    - ipBlock:
        cidr: 0.0.0.0/0  # Allow traffic from the internet (for the load balancer)
  egress:
  - to:
    - namespaceSelector: {}  # Block traffic to other namespaces

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-internet
  namespace: lost-pyramid
spec:
  podSelector:
    matchLabels:
      chal: lost-pyramid
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}  # Allow traffic within the same namespace
  - to:
    ports:
    - protocol: UDP
      port: 53  # Allow DNS traffic for name resolution
