apiVersion: v1
kind: Namespace
metadata:
  name: nix-philosophies

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nix-philosophies
  namespace: nix-philosophies
  labels:
    chal: nix-philosophies
spec:
  selector:
    matchLabels:
      chal: nix-philosophies
  template:
    metadata:
      labels:
        chal: nix-philosophies
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: nix-philosophies
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 3000
        securityContext:
          privileged: false
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false

---
apiVersion: v1
kind: Service
metadata:
  name: nix-philosophies
  namespace: nix-philosophies
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1000
      targetPort: 3000
  selector:
    chal: nix-philosophies

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nix-philosophies
  namespace: nix-philosophies
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nix-philosophies
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-other-namespaces
  namespace: nix-philosophies
spec:
  podSelector:
    matchLabels:
      chal: nix-philosophies
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}  # Allow traffic only from within the same namespace
    - ipBlock:
        cidr: 0.0.0.0/0  # Allow traffic from the internet (for the load balancer)
  egress:
  - to:
    - namespaceSelector: {}  # Block traffic to other namespaces

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-internet
  namespace: nix-philosophies
spec:
  podSelector:
    matchLabels:
      chal: nix-philosophies
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}  # Allow traffic within the same namespace
  - to:
    ports:
    - protocol: UDP
      port: 53  # Allow DNS traffic for name resolution
