apiVersion: v1
kind: Namespace
metadata:
  name: vip-blacklist

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vip-blacklist
  namespace: vip-blacklist
  labels:
    chal: vip-blacklist
spec:
  selector:
    matchLabels:
      chal: vip-blacklist
  template:
    metadata:
      labels:
        chal: vip-blacklist
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: vip-blacklist
        resources:
          requests:
            cpu: 1
            memory: 500Mi
          limits:
            cpu: 2
            memory: 1Gi
        ports:
        - containerPort: 9999
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

---
apiVersion: v1
kind: Service
metadata:
  name: vip-blacklist
  namespace: vip-blacklist
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  selector:
    chal: vip-blacklist


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vip-blacklist
  namespace: vip-blacklist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vip-blacklist
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-other-namespaces
  namespace: vip-blacklist
spec:
  podSelector:
    matchLabels:
      chal: vip-blacklist
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}  # Allow traffic only from within the same namespace
    - ipBlock:
        cidr: 0.0.0.0/0  # Allow traffic from the internet (for the load balancer)
  egress:
  - to:
    - namespaceSelector: {}  # Block traffic to other namespaces

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-internet
  namespace: vip-blacklist
spec:
  podSelector:
    matchLabels:
      chal: vip-blacklist
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}  # Allow traffic within the same namespace
  - to:
    ports:
    - protocol: UDP
      port: 53  # Allow DNS traffic for name resolution
