version: '3.8'
services:
  challenge:
    container_name: diving-into-null
    hostname: diving-into-null
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    networks:
      - no-access

networks:
  no-access:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
